variables:
  namePrefix:  ${{ replace(variables['Build.SourceBranchName'],'@','-') }}

  ${{ if contains(variables['Build.SourceBranchName'], 'release@') }}:
    version: ${{ replace(variables['Build.SourceBranchName'],'release@','') }}
  ${{ else }}:
    version: '1.0.0-alpha1'  
    
  vmImage: 'ubuntu-latest'
  buildConfiguration: 'Release'
  projectName: 'HealthForms.Api'
  sonarCloudOrganization: 'southport'
  sonarCloudProjectKey: 'southport_HealthForms.Api'
  sonarCloudProjectName: 'HealthForms.Api'